[package]
name = "client-test"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
rand = "0.9.0-alpha.1"
serde = { version = "1.0.204", features = ["derive"] }
